% To plot the data, first load all the .mat data files in this folder.
%% Distribution of all peristimulus EPSCs
binInterval = 1;  % in ms
eventBinEdges = -tBefore*1000:binInterval:tAfter*1000;
fHist = figure; subplot(2,1,1); hold on
histogram(eventTimesAll,eventBinEdges)
xlabel('Time (ms) relative to pulse onset');    ylabel('EPSC count');   box off
pdf_mixture = @(x,gamma_alpha,gamma_beta,w) ...
    w*gampdf(x,gamma_alpha,gamma_beta)+(1-w)*unifpdf(x,eventBinEdges(1),eventBinEdges(end));
startParams = [4.0253 3.1550 0.05]; upperParams = [100 100 1];   lowerParams = [0 0 0];
[paramEsts,paramCIs] = mle(eventTimesAll,'pdf',pdf_mixture,'start',startParams,'LowerBound',lowerParams,'UpperBound',upperParams);
gamma_alpha_fit = paramEsts(1);
gamma_beta_fit = paramEsts(2);
w_fit = paramEsts(3);
gamma_mu_fit = gamma_alpha_fit*gamma_beta_fit;
gamma_sigma_fit = sqrt(gamma_alpha_fit)*gamma_beta_fit;
pdf_fit_sep = w_fit*gampdf(eventBinEdges,gamma_alpha_fit,gamma_beta_fit) +...
    (1-w_fit)*unifpdf(eventBinEdges,eventBinEdges(1),eventBinEdges(end));
subplot(2,1,2); hold on
histogram(eventTimesAll,eventBinEdges,'Normalization','probability')
plot(eventBinEdges,pdf_fit_sep)
xlabel('Time (ms) relative to pulse onset');    ylabel('Density');   box off
title(['\mu_g_a_m_m_a = ' num2str(gamma_mu_fit) ', \sigma_g_a_m_m_a = ' num2str(gamma_sigma_fit) ', w = ' num2str(w_fit)])
popupmore(fHist)

%% All IO curves and all ISI curves (based on the traces with 80% of the maximal firing rate in each cell), by cell type
Ivalues = -200:50:400;  % Values to take for plotting (pA) - found in most protocols
mPFCBLA_cells.clr = [1 0 0];    rand_cells.clr = [0 0 0];   non_mPFCBLA_cells.clr = [0 0 1];
mPFCBLA_cells.n = length(mPFCBLA_cells.Rm);
rand_cells.n = length(rand_cells.Rm);
non_mPFCBLA_cells.n = length(non_mPFCBLA_cells.Rm);
mPFCBLA_cells.rateValues = zeros(mPFCBLA_cells.n,length(Ivalues));
rand_cells.rateValues = zeros(rand_cells.n,length(Ivalues));
non_mPFCBLA_cells.rateValues = zeros(non_mPFCBLA_cells.n,length(Ivalues));
for iCell = 1:mPFCBLA_cells.n
    Iround = round(mPFCBLA_cells.IOcurve(iCell).dI/10)*10;
    for iI = 1:length(Ivalues)
        Iind = find(Iround == Ivalues(iI));
        if isempty(Iind)
            mPFCBLA_cells.rateValues(iCell,iI) = NaN;
        else
            mPFCBLA_cells.rateValues(iCell,iI) = mPFCBLA_cells.IOcurve(iCell).rate(Iind);
        end
    end
end
for jCell = 1:rand_cells.n
    Iround = round(rand_cells.IOcurve(jCell).dI/10)*10;
    for jI = 1:length(Ivalues)
        Iind = find(Iround == Ivalues(jI));
        if isempty(Iind)
            rand_cells.rateValues(jCell,jI) = NaN;
        else
            rand_cells.rateValues(jCell,jI) = rand_cells.IOcurve(jCell).rate(Iind);
        end
    end
end
for kCell = 1:non_mPFCBLA_cells.n
    Iround = round(non_mPFCBLA_cells.IOcurve(kCell).dI/10)*10;
    for kI = 1:length(Ivalues)
        Iind = find(Iround == Ivalues(kI));
        if isempty(Iind)
            non_mPFCBLA_cells.rateValues(kCell,kI) = NaN;
        else
            non_mPFCBLA_cells.rateValues(kCell,kI) = non_mPFCBLA_cells.IOcurve(kCell).rate(Iind);
        end
    end
end
mPFCBLA_cells.rateMean = mean(mPFCBLA_cells.rateValues,'omitnan');
mPFCBLA_cells.rateSEM = std(mPFCBLA_cells.rateValues,'omitnan')./sqrt(sum(~isnan(mPFCBLA_cells.rateValues)));
rand_cells.rateMean = mean(rand_cells.rateValues,'omitnan');
rand_cells.rateSEM = std(rand_cells.rateValues,'omitnan')./sqrt(sum(~isnan(rand_cells.rateValues)));
non_mPFCBLA_cells.rateMean = mean(non_mPFCBLA_cells.rateValues,'omitnan');
non_mPFCBLA_cells.rateSEM = std(non_mPFCBLA_cells.rateValues,'omitnan')./sqrt(sum(~isnan(non_mPFCBLA_cells.rateValues)));
fIO = figure;   subplot(2,2,1); hold on
fill([Ivalues fliplr(Ivalues)],...
    [non_mPFCBLA_cells.rateMean+non_mPFCBLA_cells.rateSEM fliplr(non_mPFCBLA_cells.rateMean-non_mPFCBLA_cells.rateSEM)],...
    non_mPFCBLA_cells.clr+0.7*(1-non_mPFCBLA_cells.clr),'linestyle','none')
fill([Ivalues fliplr(Ivalues)],...
    [rand_cells.rateMean+rand_cells.rateSEM fliplr(rand_cells.rateMean-rand_cells.rateSEM)],...
    rand_cells.clr+0.7*(1-rand_cells.clr),'linestyle','none')
fill([Ivalues fliplr(Ivalues)],...
    [mPFCBLA_cells.rateMean+mPFCBLA_cells.rateSEM fliplr(mPFCBLA_cells.rateMean-mPFCBLA_cells.rateSEM)],...
    mPFCBLA_cells.clr+0.7*(1-mPFCBLA_cells.clr),'linestyle','none')
non_mPFCBLA_cells.plt = plot(Ivalues,non_mPFCBLA_cells.rateMean,'color',non_mPFCBLA_cells.clr);
rand_cells.plt = plot(Ivalues,rand_cells.rateMean,'color',rand_cells.clr);
mPFCBLA_cells.plt = plot(Ivalues,mPFCBLA_cells.rateMean,'color',mPFCBLA_cells.clr);
xlabel('Input current (pA)');   ylabel('Firing rate (Hz)')
legend([non_mPFCBLA_cells.plt rand_cells.plt mPFCBLA_cells.plt],{'Non-mPFC-BLA','Random mPFC','mPFC-BLA'})
subplot(2,2,3); hold on
for i = 1:non_mPFCBLA_cells.n
    plot(non_mPFCBLA_cells.IOcurve(i).dI,non_mPFCBLA_cells.IOcurve(i).rate,'color',non_mPFCBLA_cells.clr)
end
for j = 1:rand_cells.n
    plot(rand_cells.IOcurve(j).dI,rand_cells.IOcurve(j).rate,'color',rand_cells.clr)
end
for k = 1:mPFCBLA_cells.n
    plot(mPFCBLA_cells.IOcurve(k).dI,mPFCBLA_cells.IOcurve(k).rate,'color',mPFCBLA_cells.clr)
end
xlabel('I (pA)');   ylabel('Firing rate (Hz)')
ISIlengths = zeros(size(all_cells.Rm));
for ijk = 1:length(all_cells.Rm)
    ISIlengths(ijk) = length(all_cells.IOcurve(ijk).ISIat80);
end
nISIs = min(ISIlengths(ISIlengths>1))-1;    % Number of first ISIs to take, and then the last one, for consistency across cells with different firing rates
mPFCBLA_cells.ISIsNorm = nan(mPFCBLA_cells.n,nISIs+1);
rand_cells.ISIsNorm = nan(rand_cells.n,nISIs+1);
non_mPFCBLA_cells.ISIsNorm = nan(non_mPFCBLA_cells.n,nISIs+1);
subplot(2,2,4); hold on
for iCellISI = 1:non_mPFCBLA_cells.n
    ISI = non_mPFCBLA_cells.IOcurve(iCellISI).ISIat80;
    if ~isnan(ISI)
        non_mPFCBLA_cells.ISIsNorm(iCellISI,:) = [ISI(1:nISIs) ISI(end)]/ISI(1);
        plot(1:length(ISI),ISI/ISI(1),'color',non_mPFCBLA_cells.clr)
    end
end
for jCellISI = 1:rand_cells.n
    ISI = rand_cells.IOcurve(jCellISI).ISIat80;
    if ~isnan(ISI)
        rand_cells.ISIsNorm(jCellISI,:) = [ISI(1:nISIs) ISI(end)]/ISI(1);
        plot(1:length(ISI),ISI/ISI(1),'color',rand_cells.clr)
    end
end
for kCellISI = 1:mPFCBLA_cells.n
    ISI = mPFCBLA_cells.IOcurve(kCellISI).ISIat80;
    if ~isnan(ISI)
        mPFCBLA_cells.ISIsNorm(kCellISI,:) = [ISI(1:nISIs) ISI(end)]/ISI(1);
        plot(1:length(ISI),ISI/ISI(1),'color',mPFCBLA_cells.clr)
    end
end
xlabel('Interval #');   ylabel('ISI relative to 1^s^t')
subplot(2,2,2); hold on
errorbar(1:nISIs+1,mean(non_mPFCBLA_cells.ISIsNorm,'omitnan'),...
    std(non_mPFCBLA_cells.ISIsNorm,'omitnan')./sqrt(sum(~isnan(non_mPFCBLA_cells.ISIsNorm))),'color',non_mPFCBLA_cells.clr)
errorbar(1:nISIs+1,mean(rand_cells.ISIsNorm,'omitnan'),...
    std(rand_cells.ISIsNorm,'omitnan')./sqrt(sum(~isnan(rand_cells.ISIsNorm))),'color',rand_cells.clr)
errorbar(1:nISIs+1,mean(mPFCBLA_cells.ISIsNorm,'omitnan'),...
    std(mPFCBLA_cells.ISIsNorm,'omitnan')./sqrt(sum(~isnan(mPFCBLA_cells.ISIsNorm))),'color',mPFCBLA_cells.clr)
xlabel('Interval #');   ylabel('ISI relative to 1^s^t')
xticks(1:nISIs+1);  xticklabels({'1','2','3','4','5','Last'})
popupmore(fIO)

%% Connectivity inside r and inside annulus
f_conn_r_anls = figure;
annulus_centers = r_annulus(1:end-1)+(r_annulus(2)-r_annulus(1))/2;
x_lim_anls = [min([r_around_cell annulus_centers]) max([r_around_cell annulus_centers])];
side_spread = 0;
markerSizeRAnls = 12;    lineWidthRAnls = 1;  capSizeAnls = 4;
subplot(3,2,1);	hold on
errorbar(r_around_cell,mean(non_mPFCBLA_cells.conn_p.in_r,'omitnan'),std(non_mPFCBLA_cells.conn_p.in_r,'omitnan')./sqrt(sum(~isnan(non_mPFCBLA_cells.conn_p.in_r))),'linewidth',lineWidthRAnls,'markersize',10,'color',non_mPFCBLA_cells.clr,'capsize',capSizeAnls)
errorbar(r_around_cell,mean(rand_cells.conn_p.in_r,'omitnan'),std(rand_cells.conn_p.in_r,'omitnan')./sqrt(sum(~isnan(rand_cells.conn_p.in_r))),'linewidth',lineWidthRAnls,'markersize',10,'color',rand_cells.clr,'capsize',capSizeAnls)
errorbar(r_around_cell,mean(mPFCBLA_cells.conn_p.in_r,'omitnan'),std(mPFCBLA_cells.conn_p.in_r,'omitnan')./sqrt(sum(~isnan(mPFCBLA_cells.conn_p.in_r))),'linewidth',lineWidthRAnls,'markersize',10,'color',mPFCBLA_cells.clr,'capsize',capSizeAnls)
xlabel('Radius around recorded cell (\mum)');   ylabel('Prob. connection'); box off
xlim(x_lim_anls);   y_lim_anls = ylim;  ylim([0 y_lim_anls(2)])
subplot(3,2,3);	hold on
errorbar(r_around_cell,mean(non_mPFCBLA_cells.weighted_input.in_r,'omitnan'),std(non_mPFCBLA_cells.weighted_input.in_r,'omitnan')./sqrt(sum(~isnan(non_mPFCBLA_cells.weighted_input.in_r))),'linewidth',lineWidthRAnls,'markersize',10,'color',non_mPFCBLA_cells.clr,'capsize',capSizeAnls)
errorbar(r_around_cell,mean(rand_cells.weighted_input.in_r,'omitnan'),std(rand_cells.weighted_input.in_r,'omitnan')./sqrt(sum(~isnan(rand_cells.weighted_input.in_r))),'linewidth',lineWidthRAnls,'markersize',10,'color',rand_cells.clr,'capsize',capSizeAnls)
errorbar(r_around_cell,mean(mPFCBLA_cells.weighted_input.in_r,'omitnan'),std(mPFCBLA_cells.weighted_input.in_r,'omitnan')./sqrt(sum(~isnan(mPFCBLA_cells.weighted_input.in_r))),'linewidth',lineWidthRAnls,'markersize',10,'color',mPFCBLA_cells.clr,'capsize',capSizeAnls)
xlabel('Radius around recorded cell (\mum)');   ylabel('Weighted input (pA)'); box off
xlim(x_lim_anls);   y_lim_anls = ylim;  ylim([0 y_lim_anls(2)])
subplot(3,2,5);	hold on
errorbar(r_around_cell,mean(non_mPFCBLA_cells.mean_input.in_r,'omitnan'),std(non_mPFCBLA_cells.mean_input.in_r,'omitnan')./sqrt(sum(~isnan(non_mPFCBLA_cells.mean_input.in_r))),'linewidth',lineWidthRAnls,'markersize',10,'color',non_mPFCBLA_cells.clr,'capsize',capSizeAnls)
errorbar(r_around_cell,mean(rand_cells.mean_input.in_r,'omitnan'),std(rand_cells.mean_input.in_r,'omitnan')./sqrt(sum(~isnan(rand_cells.mean_input.in_r))),'linewidth',lineWidthRAnls,'markersize',10,'color',rand_cells.clr,'capsize',capSizeAnls)
errorbar(r_around_cell,mean(mPFCBLA_cells.mean_input.in_r,'omitnan'),std(mPFCBLA_cells.mean_input.in_r,'omitnan')./sqrt(sum(~isnan(mPFCBLA_cells.mean_input.in_r))),'linewidth',lineWidthRAnls,'markersize',10,'color',mPFCBLA_cells.clr,'capsize',capSizeAnls)
xlabel('Radius around recorded cell (\mum)');   ylabel('Mean conn. strength (pA)'); box off
xlim(x_lim_anls);   y_lim_anls = ylim;  ylim([0 y_lim_anls(2)])
subplot(3,2,2);	hold on
errorbar(annulus_centers+side_spread,mean(non_mPFCBLA_cells.conn_p.in_anls,'omitnan'),std(non_mPFCBLA_cells.conn_p.in_anls,'omitnan')./sqrt(sum(~isnan(non_mPFCBLA_cells.conn_p.in_anls))),'linewidth',lineWidthRAnls,'markersize',10,'color',non_mPFCBLA_cells.clr,'capsize',capSizeAnls)
errorbar(annulus_centers,mean(rand_cells.conn_p.in_anls,'omitnan'),std(rand_cells.conn_p.in_anls,'omitnan')./sqrt(sum(~isnan(rand_cells.conn_p.in_anls))),'linewidth',lineWidthRAnls,'markersize',10,'color',rand_cells.clr,'capsize',capSizeAnls)
errorbar(annulus_centers-side_spread,mean(mPFCBLA_cells.conn_p.in_anls,'omitnan'),std(mPFCBLA_cells.conn_p.in_anls,'omitnan')./sqrt(sum(~isnan(mPFCBLA_cells.conn_p.in_anls))),'linewidth',lineWidthRAnls,'markersize',10,'color',mPFCBLA_cells.clr,'capsize',capSizeAnls)
xlabel('Annulus around recorded cell (\mum)');   ylabel('Prob. connection'); box off
xlim(x_lim_anls);   y_lim_anls = ylim;  ylim([0 y_lim_anls(2)])
subplot(3,2,4);	hold on
errorbar(annulus_centers+side_spread,mean(non_mPFCBLA_cells.weighted_input.in_anls,'omitnan'),std(non_mPFCBLA_cells.weighted_input.in_anls,'omitnan')./sqrt(sum(~isnan(non_mPFCBLA_cells.weighted_input.in_anls))),'linewidth',lineWidthRAnls,'markersize',10,'color',non_mPFCBLA_cells.clr,'capsize',capSizeAnls)
errorbar(annulus_centers,mean(rand_cells.weighted_input.in_anls,'omitnan'),std(rand_cells.weighted_input.in_anls,'omitnan')./sqrt(sum(~isnan(rand_cells.weighted_input.in_anls))),'linewidth',lineWidthRAnls,'markersize',10,'color',rand_cells.clr,'capsize',capSizeAnls)
errorbar(annulus_centers-side_spread,mean(mPFCBLA_cells.weighted_input.in_anls,'omitnan'),std(mPFCBLA_cells.weighted_input.in_anls,'omitnan')./sqrt(sum(~isnan(mPFCBLA_cells.weighted_input.in_anls))),'linewidth',lineWidthRAnls,'markersize',10,'color',mPFCBLA_cells.clr,'capsize',capSizeAnls)
xlabel('Annulus around recorded cell (\mum)');   ylabel('Weighted input (pA)'); box off
xlim(x_lim_anls);   y_lim_anls = ylim;  ylim([0 y_lim_anls(2)])
subplot(3,2,6);	hold on
errorbar(annulus_centers+side_spread,mean(non_mPFCBLA_cells.mean_input.in_anls,'omitnan'),std(non_mPFCBLA_cells.mean_input.in_anls,'omitnan')./sqrt(sum(~isnan(non_mPFCBLA_cells.mean_input.in_anls))),'linewidth',lineWidthRAnls,'markersize',10,'color',non_mPFCBLA_cells.clr,'capsize',capSizeAnls)
errorbar(annulus_centers,mean(rand_cells.mean_input.in_anls,'omitnan'),std(rand_cells.mean_input.in_anls,'omitnan')./sqrt(sum(~isnan(rand_cells.mean_input.in_anls))),'linewidth',lineWidthRAnls,'markersize',10,'color',rand_cells.clr,'capsize',capSizeAnls)
errorbar(annulus_centers-side_spread,mean(mPFCBLA_cells.mean_input.in_anls,'omitnan'),std(mPFCBLA_cells.mean_input.in_anls,'omitnan')./sqrt(sum(~isnan(mPFCBLA_cells.mean_input.in_anls))),'linewidth',lineWidthRAnls,'markersize',10,'color',mPFCBLA_cells.clr,'capsize',capSizeAnls)
xlabel('Annulus around recorded cell (\mum)');   ylabel('Mean conn. strength (pA)'); box off
xlim(x_lim_anls);   y_lim_anls = ylim;  ylim([0 y_lim_anls(2)])
popupmore(f_conn_r_anls)

%% EPSC dynamics over pulses
cutoffL2L3 = 205;   % In µm from midline
cutoffL3L5 = 300;   % In µm from midline
mPFCBLA_cells.EPSCdynMean = mean(mPFCBLA_cells.connected_cells.ampPerPulse_normLast5,'omitnan');
mPFCBLA_cells.EPSCdynSEM = std(mPFCBLA_cells.connected_cells.ampPerPulse_normLast5,'omitnan')./sqrt(sum(~isnan(mPFCBLA_cells.connected_cells.ampPerPulse_normLast5)));
rand_cells.EPSCdynMean = mean(rand_cells.connected_cells.ampPerPulse_normLast5,'omitnan');
rand_cells.EPSCdynSEM = std(rand_cells.connected_cells.ampPerPulse_normLast5,'omitnan')./sqrt(sum(~isnan(rand_cells.connected_cells.ampPerPulse_normLast5)));
non_mPFCBLA_cells.EPSCdynMean = mean(non_mPFCBLA_cells.connected_cells.ampPerPulse_normLast5,'omitnan');
non_mPFCBLA_cells.EPSCdynSEM = std(non_mPFCBLA_cells.connected_cells.ampPerPulse_normLast5,'omitnan')./sqrt(sum(~isnan(non_mPFCBLA_cells.connected_cells.ampPerPulse_normLast5)));
all_cells.connected_cells.L2_indsPre = (all_cells.connected_cells.coordsPre(:,1)<=cutoffL2L3);
all_cells.connected_cells.L3_indsPre = ((all_cells.connected_cells.coordsPre(:,1)>cutoffL2L3)&(all_cells.connected_cells.coordsPre(:,1)<=cutoffL3L5));
all_cells.connected_cells.L56_indsPre = (all_cells.connected_cells.coordsPre(:,1)>cutoffL3L5);
L2Pre.EPSCdynMean = mean(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L2_indsPre,:),'omitnan');
L2Pre.EPSCdynSEM = std(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L2_indsPre,:),'omitnan')./sqrt(sum(~isnan(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L2_indsPre,:))));
L3Pre.EPSCdynMean = mean(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L3_indsPre,:),'omitnan');
L3Pre.EPSCdynSEM = std(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L3_indsPre,:),'omitnan')./sqrt(sum(~isnan(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L3_indsPre,:))));
L56Pre.EPSCdynMean = mean(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L56_indsPre,:),'omitnan');
L56Pre.EPSCdynSEM = std(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L56_indsPre,:),'omitnan')./sqrt(sum(~isnan(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L56_indsPre,:))));
all_cells.connected_cells.L2_indsPost = (all_cells.connected_cells.coordsPost(:,1)<=cutoffL2L3);
all_cells.connected_cells.L3_indsPost = ((all_cells.connected_cells.coordsPost(:,1)>cutoffL2L3)&(all_cells.connected_cells.coordsPost(:,1)<=cutoffL3L5));
all_cells.connected_cells.L56_indsPost = (all_cells.connected_cells.coordsPost(:,1)>cutoffL3L5);
L2Post.EPSCdynMean = mean(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L2_indsPost,:),'omitnan');
L2Post.EPSCdynSEM = std(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L2_indsPost,:),'omitnan')./sqrt(sum(~isnan(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L2_indsPost,:))));
L3Post.EPSCdynMean = mean(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L3_indsPost,:),'omitnan');
L3Post.EPSCdynSEM = std(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L3_indsPost,:),'omitnan')./sqrt(sum(~isnan(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L3_indsPost,:))));
L56Post.EPSCdynMean = mean(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L56_indsPost,:),'omitnan');
L56Post.EPSCdynSEM = std(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L56_indsPost,:),'omitnan')./sqrt(sum(~isnan(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L56_indsPost,:))));
L2Pre.clr = [0 0 0];   L3Pre.clr = [0 0 1];   L56Pre.clr = [1 0 0];
all_cells.connected_cells.L2toL2_inds = (all_cells.connected_cells.L2_indsPre & all_cells.connected_cells.L2_indsPost);
all_cells.connected_cells.L2toL3_inds = (all_cells.connected_cells.L2_indsPre & all_cells.connected_cells.L3_indsPost);
all_cells.connected_cells.L2toL56_inds = (all_cells.connected_cells.L2_indsPre & all_cells.connected_cells.L56_indsPost);
all_cells.connected_cells.L3toL2_inds = (all_cells.connected_cells.L3_indsPre & all_cells.connected_cells.L2_indsPost);
all_cells.connected_cells.L3toL3_inds = (all_cells.connected_cells.L3_indsPre & all_cells.connected_cells.L3_indsPost);
all_cells.connected_cells.L3toL56_inds = (all_cells.connected_cells.L3_indsPre & all_cells.connected_cells.L56_indsPost);
all_cells.connected_cells.L56toL2_inds = (all_cells.connected_cells.L56_indsPre & all_cells.connected_cells.L2_indsPost);
all_cells.connected_cells.L56toL3_inds = (all_cells.connected_cells.L56_indsPre & all_cells.connected_cells.L3_indsPost);
all_cells.connected_cells.L56toL56_inds = (all_cells.connected_cells.L56_indsPre & all_cells.connected_cells.L56_indsPost);
L2toL2.EPSCdynMean = mean(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L2toL2_inds,:),1,'omitnan');
L2toL2.EPSCdynSEM = std(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L2toL2_inds,:),0,1,'omitnan')./sqrt(sum(~isnan(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L2toL2_inds,:)),1));
L2toL3.EPSCdynMean = mean(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L2toL3_inds,:),1,'omitnan');
L2toL3.EPSCdynSEM = std(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L2toL3_inds,:),0,1,'omitnan')./sqrt(sum(~isnan(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L2toL3_inds,:)),1));
L2toL56.EPSCdynMean = mean(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L2toL56_inds,:),1,'omitnan');
L2toL56.EPSCdynSEM = std(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L2toL56_inds,:),0,1,'omitnan')./sqrt(sum(~isnan(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L2toL56_inds,:)),1));
L3toL2.EPSCdynMean = mean(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L3toL2_inds,:),1,'omitnan');
L3toL2.EPSCdynSEM = std(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L3toL2_inds,:),0,1,'omitnan')./sqrt(sum(~isnan(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L3toL2_inds,:)),1));
L3toL3.EPSCdynMean = mean(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L3toL3_inds,:),1,'omitnan');
L3toL3.EPSCdynSEM = std(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L3toL3_inds,:),0,1,'omitnan')./sqrt(sum(~isnan(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L3toL3_inds,:)),1));
L3toL56.EPSCdynMean = mean(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L3toL56_inds,:),1,'omitnan');
L3toL56.EPSCdynSEM = std(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L3toL56_inds,:),0,1,'omitnan')./sqrt(sum(~isnan(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L3toL56_inds,:)),1));
L56toL2.EPSCdynMean = mean(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L56toL2_inds,:),1,'omitnan');
L56toL2.EPSCdynSEM = std(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L56toL2_inds,:),0,1,'omitnan')./sqrt(sum(~isnan(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L56toL2_inds,:)),1));
L56toL3.EPSCdynMean = mean(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L56toL3_inds,:),1,'omitnan');
L56toL3.EPSCdynSEM = std(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L56toL3_inds,:),0,1,'omitnan')./sqrt(sum(~isnan(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L56toL3_inds,:)),1));
L56toL56.EPSCdynMean = mean(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L56toL56_inds,:),1,'omitnan');
L56toL56.EPSCdynSEM = std(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L56toL56_inds,:),0,1,'omitnan')./sqrt(sum(~isnan(all_cells.connected_cells.ampPerPulse_normLast5(all_cells.connected_cells.L56toL56_inds,:)),1));
y_lim_EPSCdyn = [0.5 2.25]; y_ticks = y_lim_EPSCdyn(1):0.5:y_lim_EPSCdyn(2);
fEPSCdyn = figure;  set(gcf,'Position',[98.6 105 1242.4 657])
subplot(2,3,1); hold on
fill([1:max_spirals fliplr(1:max_spirals)],...
    [rand_cells.EPSCdynMean+rand_cells.EPSCdynSEM fliplr(rand_cells.EPSCdynMean-rand_cells.EPSCdynSEM)],...
    rand_cells.clr,'FaceAlpha',0.3,'linestyle','none')
fill([1:max_spirals fliplr(1:max_spirals)],...
    [non_mPFCBLA_cells.EPSCdynMean+non_mPFCBLA_cells.EPSCdynSEM fliplr(non_mPFCBLA_cells.EPSCdynMean-non_mPFCBLA_cells.EPSCdynSEM)],...
    non_mPFCBLA_cells.clr,'FaceAlpha',0.3,'linestyle','none')
fill([1:max_spirals fliplr(1:max_spirals)],...
    [mPFCBLA_cells.EPSCdynMean+mPFCBLA_cells.EPSCdynSEM fliplr(mPFCBLA_cells.EPSCdynMean-mPFCBLA_cells.EPSCdynSEM)],...
    mPFCBLA_cells.clr,'FaceAlpha',0.3,'linestyle','none')
rand_cells.pltEPSCdyn = plot(1:max_spirals,rand_cells.EPSCdynMean,'color',rand_cells.clr);
non_mPFCBLA_cells.pltEPSCdyn = plot(1:max_spirals,non_mPFCBLA_cells.EPSCdynMean,'color',non_mPFCBLA_cells.clr);
mPFCBLA_cells.pltEPSCdyn = plot(1:max_spirals,mPFCBLA_cells.EPSCdynMean,'color',mPFCBLA_cells.clr);
xlabel('Pulse #');  ylabel('EPSC amplitude (norm.)');    title('Map type')
legend([rand_cells.pltEPSCdyn,non_mPFCBLA_cells.pltEPSCdyn,mPFCBLA_cells.pltEPSCdyn],{'Random','Non-mPFC-BLA','mPFC-BLA'})
xlim([1 max_spirals]);  ylim(y_lim_EPSCdyn)
xticks(1:max_spirals);  yticks(y_ticks)
subplot(2,3,2); hold on
fill([1:max_spirals fliplr(1:max_spirals)],...
    [L2Pre.EPSCdynMean+L2Pre.EPSCdynSEM fliplr(L2Pre.EPSCdynMean-L2Pre.EPSCdynSEM)],...
    L2Pre.clr,'FaceAlpha',0.3,'linestyle','none')
fill([1:max_spirals fliplr(1:max_spirals)],...
    [L3Pre.EPSCdynMean+L3Pre.EPSCdynSEM fliplr(L3Pre.EPSCdynMean-L3Pre.EPSCdynSEM)],...
    L3Pre.clr,'FaceAlpha',0.3,'linestyle','none')
fill([1:max_spirals fliplr(1:max_spirals)],...
    [L56Pre.EPSCdynMean+L56Pre.EPSCdynSEM fliplr(L56Pre.EPSCdynMean-L56Pre.EPSCdynSEM)],...
    L56Pre.clr,'FaceAlpha',0.3,'linestyle','none')
L2Pre.pltEPSCdyn = plot(1:max_spirals,L2Pre.EPSCdynMean,'color',L2Pre.clr);
L3Pre.pltEPSCdyn = plot(1:max_spirals,L3Pre.EPSCdynMean,'color',L3Pre.clr);
L56Pre.pltEPSCdyn = plot(1:max_spirals,L56Pre.EPSCdynMean,'color',L56Pre.clr);
xlabel('Pulse #');  ylabel('EPSC amplitude (norm.)');    title('Layer of presynaptic cells')
legend([L2Pre.pltEPSCdyn,L3Pre.pltEPSCdyn,L56Pre.pltEPSCdyn],{'L2','L3','L56'})
xlim([1 max_spirals]);  ylim(y_lim_EPSCdyn)
xticks(1:max_spirals);  yticks(y_ticks)
subplot(2,3,3); hold on
fill([1:max_spirals fliplr(1:max_spirals)],...
    [L2Post.EPSCdynMean+L2Post.EPSCdynSEM fliplr(L2Post.EPSCdynMean-L2Post.EPSCdynSEM)],...
    L2Pre.clr,'FaceAlpha',0.3,'linestyle','none')
fill([1:max_spirals fliplr(1:max_spirals)],...
    [L3Post.EPSCdynMean+L3Post.EPSCdynSEM fliplr(L3Post.EPSCdynMean-L3Post.EPSCdynSEM)],...
    L3Pre.clr,'FaceAlpha',0.3,'linestyle','none')
fill([1:max_spirals fliplr(1:max_spirals)],...
    [L56Post.EPSCdynMean+L56Post.EPSCdynSEM fliplr(L56Post.EPSCdynMean-L56Post.EPSCdynSEM)],...
    L56Pre.clr,'FaceAlpha',0.3,'linestyle','none')
L2Post.pltEPSCdyn = plot(1:max_spirals,L2Post.EPSCdynMean,'color',L2Pre.clr);
L3Post.pltEPSCdyn = plot(1:max_spirals,L3Post.EPSCdynMean,'color',L3Pre.clr);
L56Post.pltEPSCdyn = plot(1:max_spirals,L56Post.EPSCdynMean,'color',L56Pre.clr);
xlabel('Pulse #');  ylabel('EPSC amplitude (norm.)');    title('Layer of postsynaptic cells')
legend([L2Post.pltEPSCdyn,L3Pre.pltEPSCdyn,L56Post.pltEPSCdyn],{'L2','L3','L56'})
xlim([1 max_spirals]);  ylim(y_lim_EPSCdyn)
xticks(1:max_spirals);  yticks(y_ticks)
subplot(2,3,4); hold on
fill([1:max_spirals fliplr(1:max_spirals)],...
    [L2toL2.EPSCdynMean+L2toL2.EPSCdynSEM fliplr(L2toL2.EPSCdynMean-L2toL2.EPSCdynSEM)],...
    L2Pre.clr,'FaceAlpha',0.3,'linestyle','none')
fill([1:max_spirals fliplr(1:max_spirals)],...
    [L3toL2.EPSCdynMean+L3toL2.EPSCdynSEM fliplr(L3toL2.EPSCdynMean-L3toL2.EPSCdynSEM)],...
    L3Pre.clr,'FaceAlpha',0.3,'linestyle','none')
fill([1:max_spirals fliplr(1:max_spirals)],...
    [L56toL2.EPSCdynMean+L56toL2.EPSCdynSEM fliplr(L56toL2.EPSCdynMean-L56toL2.EPSCdynSEM)],...
    L56Pre.clr,'FaceAlpha',0.3,'linestyle','none')
L2toL2.pltEPSCdyn = plot(1:max_spirals,L2toL2.EPSCdynMean,'color',L2Pre.clr);
L3toL2.pltEPSCdyn = plot(1:max_spirals,L3toL2.EPSCdynMean,'color',L3Pre.clr);
L56toL2.pltEPSCdyn = plot(1:max_spirals,L56toL2.EPSCdynMean,'color',L56Pre.clr);
xlabel('Pulse #');  ylabel('EPSC amplitude (norm.)');    title('LX to L2')
legend([L2toL2.pltEPSCdyn,L3toL2.pltEPSCdyn,L56toL2.pltEPSCdyn],{'L2','L3','L56'})
xlim([1 max_spirals]);  ylim(y_lim_EPSCdyn)
xticks(1:max_spirals);  yticks(y_ticks)
subplot(2,3,5); hold on
fill([1:max_spirals fliplr(1:max_spirals)],...
    [L2toL3.EPSCdynMean+L2toL3.EPSCdynSEM fliplr(L2toL3.EPSCdynMean-L2toL3.EPSCdynSEM)],...
    L2Pre.clr,'FaceAlpha',0.3,'linestyle','none')
fill([1:max_spirals fliplr(1:max_spirals)],...
    [L3toL3.EPSCdynMean+L3toL3.EPSCdynSEM fliplr(L3toL3.EPSCdynMean-L3toL3.EPSCdynSEM)],...
    L3Pre.clr,'FaceAlpha',0.3,'linestyle','none')
fill([1:max_spirals fliplr(1:max_spirals)],...
    [L56toL3.EPSCdynMean+L56toL3.EPSCdynSEM fliplr(L56toL3.EPSCdynMean-L56toL3.EPSCdynSEM)],...
    L56Pre.clr,'FaceAlpha',0.3,'linestyle','none')
L2toL3.pltEPSCdyn = plot(1:max_spirals,L2toL3.EPSCdynMean,'color',L2Pre.clr);
L3toL3.pltEPSCdyn = plot(1:max_spirals,L3toL3.EPSCdynMean,'color',L3Pre.clr);
L56toL3.pltEPSCdyn = plot(1:max_spirals,L56toL3.EPSCdynMean,'color',L56Pre.clr);
xlabel('Pulse #');  ylabel('EPSC amplitude (norm.)');    title('LX to L3')
legend([L2toL3.pltEPSCdyn,L3toL3.pltEPSCdyn,L56toL3.pltEPSCdyn],{'L2','L3','L56'})
xlim([1 max_spirals]);  ylim(y_lim_EPSCdyn)
xticks(1:max_spirals);  yticks(y_ticks)
subplot(2,3,6); hold on
fill([1:max_spirals fliplr(1:max_spirals)],...
    [L2toL56.EPSCdynMean+L2toL56.EPSCdynSEM fliplr(L2toL56.EPSCdynMean-L2toL56.EPSCdynSEM)],...
    L2Pre.clr,'FaceAlpha',0.3,'linestyle','none')
fill([1:max_spirals fliplr(1:max_spirals)],...
    [L3toL56.EPSCdynMean+L3toL56.EPSCdynSEM fliplr(L3toL56.EPSCdynMean-L3toL56.EPSCdynSEM)],...
    L3Pre.clr,'FaceAlpha',0.3,'linestyle','none')
fill([1:max_spirals fliplr(1:max_spirals)],...
    [L56toL56.EPSCdynMean+L56toL56.EPSCdynSEM fliplr(L56toL56.EPSCdynMean-L56toL56.EPSCdynSEM)],...
    L56Pre.clr,'FaceAlpha',0.3,'linestyle','none')
L2toL56.pltEPSCdyn = plot(1:max_spirals,L2toL56.EPSCdynMean,'color',L2Pre.clr);
L3toL56.pltEPSCdyn = plot(1:max_spirals,L3toL56.EPSCdynMean,'color',L3Pre.clr);
L56toL56.pltEPSCdyn = plot(1:max_spirals,L56toL56.EPSCdynMean,'color',L56Pre.clr);
xlabel('Pulse #');  ylabel('EPSC amplitude (norm.)');    title('LX to L56')
legend([L2toL56.pltEPSCdyn,L3toL56.pltEPSCdyn,L56toL56.pltEPSCdyn],{'L2','L3','L56'})
xlim([1 max_spirals]);  ylim(y_lim_EPSCdyn)
xticks(1:max_spirals);  yticks(y_ticks)
popupmore(fEPSCdyn)

%% Connection probability vs. amplitude with regression line
plotSpreadBinWidth = 0.3;   plotSpreadMarkerSize = 8;
cutoffL2L3 = 205;   % In µm from midline
cutoffL3L5 = 300;   % In µm from midline
selected_r = 300;   % In µm, radius within which to plot the prob of connection
mPFCBLA_cells.clr = [1 0 0];
rand_cells.clr = [0 0 0];
non_mPFCBLA_cells.clr = [0 0 1];
all_cells.clr = zeros(size(all_cells.cellType,1),3);
all_cells.clr(cellfun(@(c)strcmp(c,'mPFC-BLA'),all_cells.cellType),1) = 1;
all_cells.clr(cellfun(@(c)strcmp(c,'non-mPFC-BLA'),all_cells.cellType),3) = 1;
mPFCBLA_cells.n = length(mPFCBLA_cells.Rm); rand_cells.n = length(rand_cells.Rm);   non_mPFCBLA_cells.n = length(non_mPFCBLA_cells.Rm);
r_ind_slct = find(r_around_cell == selected_r);
[~,r_ind_max] = max(r_around_cell);
mPFCBLA_cells.L2_inds = mPFCBLA_cells.recorded_cells_coords(:,1) <= cutoffL2L3;
mPFCBLA_cells.L3_inds = (mPFCBLA_cells.recorded_cells_coords(:,1) > cutoffL2L3) & (mPFCBLA_cells.recorded_cells_coords(:,1) <= cutoffL3L5);
mPFCBLA_cells.L56_inds = mPFCBLA_cells.recorded_cells_coords(:,1) > cutoffL3L5;
rand_cells.L2_inds = rand_cells.recorded_cells_coords(:,1) <= cutoffL2L3;
rand_cells.L3_inds = (rand_cells.recorded_cells_coords(:,1) > cutoffL2L3) & (rand_cells.recorded_cells_coords(:,1) <= cutoffL3L5);
rand_cells.L56_inds = rand_cells.recorded_cells_coords(:,1) > cutoffL3L5;
non_mPFCBLA_cells.L2_inds = non_mPFCBLA_cells.recorded_cells_coords(:,1) <= cutoffL2L3;
non_mPFCBLA_cells.L3_inds = (non_mPFCBLA_cells.recorded_cells_coords(:,1) > cutoffL2L3) & (non_mPFCBLA_cells.recorded_cells_coords(:,1) <= cutoffL3L5);
non_mPFCBLA_cells.L56_inds = non_mPFCBLA_cells.recorded_cells_coords(:,1) > cutoffL3L5;
sctrSz = 7;	sctrLnWidth = 1;
fEphysProps = figure;
subplot(3,5,1); hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_cells.conn_p.in_r(:,r_ind_slct),'omitnan') mean(non_mPFCBLA_cells.conn_p.in_r(:,r_ind_slct),'omitnan') mean(rand_cells.conn_p.in_r(:,r_ind_slct),'omitnan')],...
    [std(mPFCBLA_cells.conn_p.in_r(:,r_ind_slct),'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.conn_p.in_r(:,r_ind_slct)))),...
    std(non_mPFCBLA_cells.conn_p.in_r(:,r_ind_slct),'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.conn_p.in_r(:,r_ind_slct)))),...
    std(rand_cells.conn_p.in_r(:,r_ind_slct),'omitnan')/sqrt(sum(~isnan(rand_cells.conn_p.in_r(:,r_ind_slct))))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',7)
plotSpread({mPFCBLA_cells.conn_p.in_r(:,r_ind_slct),non_mPFCBLA_cells.conn_p.in_r(:,r_ind_slct),rand_cells.conn_p.in_r(:,r_ind_slct)},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','Rand'})
ylabel(['P(conn) in r=' num2str(selected_r) ' \mum'])
[p_kw,tbl_kw,stats_kw] = kruskalwallis([mPFCBLA_cells.conn_p.in_r(:,r_ind_slct);rand_cells.conn_p.in_r(:,r_ind_slct);non_mPFCBLA_cells.conn_p.in_r(:,r_ind_slct)],...
    [repmat({'mPFC-BLA'},size(mPFCBLA_cells.conn_p.in_r(:,r_ind_slct)));repmat({'Random'},size(rand_cells.conn_p.in_r(:,r_ind_slct)));repmat({'Non-mPFC-BLA'},size(non_mPFCBLA_cells.conn_p.in_r(:,r_ind_slct)))],'off');
c_kw = multcompare(stats_kw,'Display','off');
title(['p_m_B_-_v_s_-_r_n_d = ' num2str(c_kw(1,6),3) '; p_m_B_-_v_s_-_n_-_m_B = ' num2str(c_kw(2,6),3) '; p_r_n_d_-_v_s_-_n_-_m_B = ' num2str(c_kw(3,6),3)])
subplot(3,5,2); hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_cells.weighted_input.in_r(:,r_ind_slct),'omitnan') mean(non_mPFCBLA_cells.weighted_input.in_r(:,r_ind_slct),'omitnan') mean(rand_cells.weighted_input.in_r(:,r_ind_slct),'omitnan')],...
    [std(mPFCBLA_cells.weighted_input.in_r(:,r_ind_slct),'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.weighted_input.in_r(:,r_ind_slct)))),...
    std(non_mPFCBLA_cells.weighted_input.in_r(:,r_ind_slct),'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.weighted_input.in_r(:,r_ind_slct)))),...
    std(rand_cells.weighted_input.in_r(:,r_ind_slct),'omitnan')/sqrt(sum(~isnan(rand_cells.weighted_input.in_r(:,r_ind_slct))))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',7)
plotSpread({mPFCBLA_cells.weighted_input.in_r(:,r_ind_slct),non_mPFCBLA_cells.weighted_input.in_r(:,r_ind_slct),rand_cells.weighted_input.in_r(:,r_ind_slct)},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','Rand'})
ylabel(['Weighted input (pA) in r=' num2str(selected_r) ' \mum'])
[p_kw,tbl_kw,stats_kw] = kruskalwallis([mPFCBLA_cells.weighted_input.in_r(:,r_ind_slct);rand_cells.weighted_input.in_r(:,r_ind_slct);non_mPFCBLA_cells.weighted_input.in_r(:,r_ind_slct)],...
    [repmat({'mPFC-BLA'},size(mPFCBLA_cells.weighted_input.in_r(:,r_ind_slct)));repmat({'Random'},size(rand_cells.weighted_input.in_r(:,r_ind_slct)));repmat({'Non-mPFC-BLA'},size(non_mPFCBLA_cells.weighted_input.in_r(:,r_ind_slct)))],'off');
c_kw = multcompare(stats_kw,'Display','off');
title(['p_m_B_-_v_s_-_r_n_d = ' num2str(c_kw(1,6),3) '; p_m_B_-_v_s_-_n_-_m_B = ' num2str(c_kw(2,6),3) '; p_r_n_d_-_v_s_-_n_-_m_B = ' num2str(c_kw(3,6),3)])
subplot(3,5,3); hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_cells.mean_input.in_r(:,r_ind_max),'omitnan') mean(non_mPFCBLA_cells.mean_input.in_r(:,r_ind_max),'omitnan') mean(rand_cells.mean_input.in_r(:,r_ind_max),'omitnan')],...
    [std(mPFCBLA_cells.mean_input.in_r(:,r_ind_max),'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.mean_input.in_r(:,r_ind_max)))),...
    std(non_mPFCBLA_cells.mean_input.in_r(:,r_ind_max),'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.mean_input.in_r(:,r_ind_max)))),...
    std(rand_cells.mean_input.in_r(:,r_ind_max),'omitnan')/sqrt(sum(~isnan(rand_cells.mean_input.in_r(:,r_ind_max))))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',7)
plotSpread({mPFCBLA_cells.mean_input.in_r(:,r_ind_max),non_mPFCBLA_cells.mean_input.in_r(:,r_ind_max),rand_cells.mean_input.in_r(:,r_ind_max)},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','Rand'})
ylabel('Mean conn. strength (pA)')
[p_kw,tbl_kw,stats_kw] = kruskalwallis([mPFCBLA_cells.mean_input.in_r(:,r_ind_max);rand_cells.mean_input.in_r(:,r_ind_max);non_mPFCBLA_cells.mean_input.in_r(:,r_ind_max)],...
    [repmat({'mPFC-BLA'},size(mPFCBLA_cells.mean_input.in_r(:,r_ind_max)));repmat({'Random'},size(rand_cells.mean_input.in_r(:,r_ind_max)));repmat({'Non-mPFC-BLA'},size(non_mPFCBLA_cells.mean_input.in_r(:,r_ind_max)))],'off');
c_kw = multcompare(stats_kw,'Display','off');
title(['p_m_B_-_v_s_-_r_n_d = ' num2str(c_kw(1,6),3) '; p_m_B_-_v_s_-_n_-_m_B = ' num2str(c_kw(2,6),3) '; p_r_n_d_-_v_s_-_n_-_m_B = ' num2str(c_kw(3,6),3)])
subplot(3,5,4); hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_cells.maxFireRate,'omitnan') mean(non_mPFCBLA_cells.maxFireRate,'omitnan') mean(rand_cells.maxFireRate,'omitnan')],...
    [std(mPFCBLA_cells.maxFireRate,'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.maxFireRate))),...
    std(non_mPFCBLA_cells.maxFireRate,'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.maxFireRate))),...
    std(rand_cells.maxFireRate,'omitnan')/sqrt(sum(~isnan(rand_cells.maxFireRate)))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',7)
plotSpread({mPFCBLA_cells.maxFireRate,non_mPFCBLA_cells.maxFireRate,rand_cells.maxFireRate},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','Rand'})
ylabel('Max firing rate (Hz)')
[p_kw,tbl_kw,stats_kw] = kruskalwallis([mPFCBLA_cells.maxFireRate;rand_cells.maxFireRate;non_mPFCBLA_cells.maxFireRate],...
    [repmat({'mPFC-BLA'},size(mPFCBLA_cells.maxFireRate));repmat({'Random'},size(rand_cells.maxFireRate));repmat({'Non-mPFC-BLA'},size(non_mPFCBLA_cells.maxFireRate))],'off');
c_kw = multcompare(stats_kw,'Display','off');
title(['p_m_B_-_v_s_-_r_n_d = ' num2str(c_kw(1,6),3) '; p_m_B_-_v_s_-_n_-_m_B = ' num2str(c_kw(2,6),3) '; p_r_n_d_-_v_s_-_n_-_m_B = ' num2str(c_kw(3,6),3)])
subplot(3,5,5); hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_cells.Rm,'omitnan') mean(non_mPFCBLA_cells.Rm,'omitnan') mean(rand_cells.Rm,'omitnan')],...
    [std(mPFCBLA_cells.Rm,'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.Rm))),...
    std(non_mPFCBLA_cells.Rm,'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.Rm))),...
    std(rand_cells.Rm,'omitnan')/sqrt(sum(~isnan(rand_cells.Rm)))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',7)
plotSpread({mPFCBLA_cells.Rm,non_mPFCBLA_cells.Rm,rand_cells.Rm},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','Rand'})
ylabel('Rm (M\Omega)')
[p_kw,tbl_kw,stats_kw] = kruskalwallis([mPFCBLA_cells.Rm;rand_cells.Rm;non_mPFCBLA_cells.Rm],...
    [repmat({'mPFC-BLA'},size(mPFCBLA_cells.Rm));repmat({'Random'},size(rand_cells.Rm));repmat({'Non-mPFC-BLA'},size(non_mPFCBLA_cells.Rm))],'off');
c_kw = multcompare(stats_kw,'Display','off');
title(['p_m_B_-_v_s_-_r_n_d = ' num2str(c_kw(1,6),3) '; p_m_B_-_v_s_-_n_-_m_B = ' num2str(c_kw(2,6),3) '; p_r_n_d_-_v_s_-_n_-_m_B = ' num2str(c_kw(3,6),3)])
subplot(3,5,6); hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_cells.Cm,'omitnan') mean(non_mPFCBLA_cells.Cm,'omitnan') mean(rand_cells.Cm,'omitnan')],...
    [std(mPFCBLA_cells.Cm,'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.Cm))),...
    std(non_mPFCBLA_cells.Cm,'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.Cm))),...
    std(rand_cells.Cm,'omitnan')/sqrt(sum(~isnan(rand_cells.Cm)))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',7)
plotSpread({mPFCBLA_cells.Cm,non_mPFCBLA_cells.Cm,rand_cells.Cm},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','Rand'})
ylabel('Cm (pF)')
[p_kw,tbl_kw,stats_kw] = kruskalwallis([mPFCBLA_cells.Cm;rand_cells.Cm;non_mPFCBLA_cells.Cm],...
    [repmat({'mPFC-BLA'},size(mPFCBLA_cells.Cm));repmat({'Random'},size(rand_cells.Cm));repmat({'Non-mPFC-BLA'},size(non_mPFCBLA_cells.Cm))],'off');
c_kw = multcompare(stats_kw,'Display','off');
title(['p_m_B_-_v_s_-_r_n_d = ' num2str(c_kw(1,6),3) '; p_m_B_-_v_s_-_n_-_m_B = ' num2str(c_kw(2,6),3) '; p_r_n_d_-_v_s_-_n_-_m_B = ' num2str(c_kw(3,6),3)])
subplot(3,5,7); hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_cells.sagRatio,'omitnan') mean(non_mPFCBLA_cells.sagRatio,'omitnan') mean(rand_cells.sagRatio,'omitnan')],...
    [std(mPFCBLA_cells.sagRatio,'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.sagRatio))),...
    std(non_mPFCBLA_cells.sagRatio,'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.sagRatio))),...
    std(rand_cells.sagRatio,'omitnan')/sqrt(sum(~isnan(rand_cells.sagRatio)))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',7)
plotSpread({mPFCBLA_cells.sagRatio,non_mPFCBLA_cells.sagRatio,rand_cells.sagRatio},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','Rand'})
ylabel('Sag ratio')
[p_kw,tbl_kw,stats_kw] = kruskalwallis([mPFCBLA_cells.sagRatio;rand_cells.sagRatio;non_mPFCBLA_cells.sagRatio],...
    [repmat({'mPFC-BLA'},size(mPFCBLA_cells.sagRatio));repmat({'Random'},size(rand_cells.sagRatio));repmat({'Non-mPFC-BLA'},size(non_mPFCBLA_cells.sagRatio))],'off');
c_kw = multcompare(stats_kw,'Display','off');
title(['p_m_B_-_v_s_-_r_n_d = ' num2str(c_kw(1,6),3) '; p_m_B_-_v_s_-_n_-_m_B = ' num2str(c_kw(2,6),3) '; p_r_n_d_-_v_s_-_n_-_m_B = ' num2str(c_kw(3,6),3)])
subplot(3,5,8); hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_cells.spikeWidth,'omitnan') mean(non_mPFCBLA_cells.spikeWidth,'omitnan') mean(rand_cells.spikeWidth,'omitnan')],...
    [std(mPFCBLA_cells.spikeWidth,'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.spikeWidth))),...
    std(non_mPFCBLA_cells.spikeWidth,'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.spikeWidth))),...
    std(rand_cells.spikeWidth,'omitnan')/sqrt(sum(~isnan(rand_cells.spikeWidth)))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',7)
plotSpread({mPFCBLA_cells.spikeWidth,non_mPFCBLA_cells.spikeWidth,rand_cells.spikeWidth},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','Rand'})
ylabel('Spike half-width (ms)')
[p_kw,tbl_kw,stats_kw] = kruskalwallis([mPFCBLA_cells.spikeWidth;rand_cells.spikeWidth;non_mPFCBLA_cells.spikeWidth],...
    [repmat({'mPFC-BLA'},size(mPFCBLA_cells.spikeWidth));repmat({'Random'},size(rand_cells.spikeWidth));repmat({'Non-mPFC-BLA'},size(non_mPFCBLA_cells.spikeWidth))],'off');
c_kw = multcompare(stats_kw,'Display','off');
title(['p_m_B_-_v_s_-_r_n_d = ' num2str(c_kw(1,6),3) '; p_m_B_-_v_s_-_n_-_m_B = ' num2str(c_kw(2,6),3) '; p_r_n_d_-_v_s_-_n_-_m_B = ' num2str(c_kw(3,6),3)])
subplot(3,5,9); hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_cells.adaptIndex,'omitnan') mean(non_mPFCBLA_cells.adaptIndex,'omitnan') mean(rand_cells.adaptIndex,'omitnan')],...
    [std(mPFCBLA_cells.adaptIndex,'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.adaptIndex))),...
    std(non_mPFCBLA_cells.adaptIndex,'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.adaptIndex))),...
    std(rand_cells.adaptIndex,'omitnan')/sqrt(sum(~isnan(rand_cells.adaptIndex)))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',7)
plotSpread({mPFCBLA_cells.adaptIndex,non_mPFCBLA_cells.adaptIndex,rand_cells.adaptIndex},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','Rand'})
ylabel('Adaptation index')
[p_kw,tbl_kw,stats_kw] = kruskalwallis([mPFCBLA_cells.adaptIndex;rand_cells.adaptIndex;non_mPFCBLA_cells.adaptIndex],...
    [repmat({'mPFC-BLA'},size(mPFCBLA_cells.adaptIndex));repmat({'Random'},size(rand_cells.adaptIndex));repmat({'Non-mPFC-BLA'},size(non_mPFCBLA_cells.adaptIndex))],'off');
c_kw = multcompare(stats_kw,'Display','off');
title(['p_m_B_-_v_s_-_r_n_d = ' num2str(c_kw(1,6),3) '; p_m_B_-_v_s_-_n_-_m_B = ' num2str(c_kw(2,6),3) '; p_r_n_d_-_v_s_-_n_-_m_B = ' num2str(c_kw(3,6),3)])
subplot(3,5,10); hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_cells.burstIndex,'omitnan') mean(non_mPFCBLA_cells.burstIndex,'omitnan') mean(rand_cells.burstIndex,'omitnan')],...
    [std(mPFCBLA_cells.burstIndex,'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.burstIndex))),...
    std(non_mPFCBLA_cells.burstIndex,'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.burstIndex))),...
    std(rand_cells.burstIndex,'omitnan')/sqrt(sum(~isnan(rand_cells.burstIndex)))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',7)
plotSpread({mPFCBLA_cells.burstIndex,non_mPFCBLA_cells.burstIndex,rand_cells.burstIndex},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','Rand'})
ylabel('Bursting index')
[p_kw,tbl_kw,stats_kw] = kruskalwallis([mPFCBLA_cells.burstIndex;rand_cells.burstIndex;non_mPFCBLA_cells.burstIndex],...
    [repmat({'mPFC-BLA'},size(mPFCBLA_cells.burstIndex));repmat({'Random'},size(rand_cells.burstIndex));repmat({'Non-mPFC-BLA'},size(non_mPFCBLA_cells.burstIndex))],'off');
c_kw = multcompare(stats_kw,'Display','off');
title(['p_m_B_-_v_s_-_r_n_d = ' num2str(c_kw(1,6),3) '; p_m_B_-_v_s_-_n_-_m_B = ' num2str(c_kw(2,6),3) '; p_r_n_d_-_v_s_-_n_-_m_B = ' num2str(c_kw(3,6),3)])
subplot(3,5,11); hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_cells.spikeThresh,'omitnan') mean(non_mPFCBLA_cells.spikeThresh,'omitnan') mean(rand_cells.spikeThresh,'omitnan')],...
    [std(mPFCBLA_cells.spikeThresh,'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.spikeThresh))),...
    std(non_mPFCBLA_cells.spikeThresh,'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.spikeThresh))),...
    std(rand_cells.spikeThresh,'omitnan')/sqrt(sum(~isnan(rand_cells.spikeThresh)))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',7)
plotSpread({mPFCBLA_cells.spikeThresh,non_mPFCBLA_cells.spikeThresh,rand_cells.spikeThresh},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','Rand'})
ylabel('Spike threshold (mV)')
[p_kw,tbl_kw,stats_kw] = kruskalwallis([mPFCBLA_cells.spikeThresh;rand_cells.spikeThresh;non_mPFCBLA_cells.spikeThresh],...
    [repmat({'mPFC-BLA'},size(mPFCBLA_cells.spikeThresh));repmat({'Random'},size(rand_cells.spikeThresh));repmat({'Non-mPFC-BLA'},size(non_mPFCBLA_cells.spikeThresh))],'off');
c_kw = multcompare(stats_kw,'Display','off');
title(['p_m_B_-_v_s_-_r_n_d = ' num2str(c_kw(1,6),3) '; p_m_B_-_v_s_-_n_-_m_B = ' num2str(c_kw(2,6),3) '; p_r_n_d_-_v_s_-_n_-_m_B = ' num2str(c_kw(3,6),3)])
subplot(3,5,12); hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_cells.spikeAmp,'omitnan') mean(non_mPFCBLA_cells.spikeAmp,'omitnan') mean(rand_cells.spikeAmp,'omitnan')],...
    [std(mPFCBLA_cells.spikeAmp,'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.spikeAmp))),...
    std(non_mPFCBLA_cells.spikeAmp,'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.spikeAmp))),...
    std(rand_cells.spikeAmp,'omitnan')/sqrt(sum(~isnan(rand_cells.spikeAmp)))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',7)
plotSpread({mPFCBLA_cells.spikeAmp,non_mPFCBLA_cells.spikeAmp,rand_cells.spikeAmp},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','Rand'})
ylabel('Spike amplitude (mV)')
[p_kw,tbl_kw,stats_kw] = kruskalwallis([mPFCBLA_cells.spikeAmp;rand_cells.spikeAmp;non_mPFCBLA_cells.spikeAmp],...
    [repmat({'mPFC-BLA'},size(mPFCBLA_cells.spikeAmp));repmat({'Random'},size(rand_cells.spikeAmp));repmat({'Non-mPFC-BLA'},size(non_mPFCBLA_cells.spikeAmp))],'off');
c_kw = multcompare(stats_kw,'Display','off');
title(['p_m_B_-_v_s_-_r_n_d = ' num2str(c_kw(1,6),3) '; p_m_B_-_v_s_-_n_-_m_B = ' num2str(c_kw(2,6),3) '; p_r_n_d_-_v_s_-_n_-_m_B = ' num2str(c_kw(3,6),3)])
subplot(3,5,13); hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_cells.outputGain,'omitnan') mean(non_mPFCBLA_cells.outputGain,'omitnan') mean(rand_cells.outputGain,'omitnan')],...
    [std(mPFCBLA_cells.outputGain,'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.outputGain))),...
    std(non_mPFCBLA_cells.outputGain,'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.outputGain))),...
    std(rand_cells.outputGain,'omitnan')/sqrt(sum(~isnan(rand_cells.outputGain)))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',7)
plotSpread({mPFCBLA_cells.outputGain,non_mPFCBLA_cells.outputGain,rand_cells.outputGain},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','Rand'})
ylabel('Output gain (Hz/pA)')
[p_kw,tbl_kw,stats_kw] = kruskalwallis([mPFCBLA_cells.outputGain;rand_cells.outputGain;non_mPFCBLA_cells.outputGain],...
    [repmat({'mPFC-BLA'},size(mPFCBLA_cells.outputGain));repmat({'Random'},size(rand_cells.outputGain));repmat({'Non-mPFC-BLA'},size(non_mPFCBLA_cells.outputGain))],'off');
c_kw = multcompare(stats_kw,'Display','off');
title(['p_m_B_-_v_s_-_r_n_d = ' num2str(c_kw(1,6),3) '; p_m_B_-_v_s_-_n_-_m_B = ' num2str(c_kw(2,6),3) '; p_r_n_d_-_v_s_-_n_-_m_B = ' num2str(c_kw(3,6),3)])
subplot(3,5,14);	hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_cells.Vclamp,'omitnan') mean(non_mPFCBLA_cells.Vclamp,'omitnan') mean(rand_cells.Vclamp,'omitnan')],...
    [std(mPFCBLA_cells.Vclamp,'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.Vclamp))),...
    std(non_mPFCBLA_cells.Vclamp,'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.Vclamp))),...
    std(rand_cells.Vclamp,'omitnan')/sqrt(sum(~isnan(rand_cells.Vclamp)))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',7)
plotSpread({mPFCBLA_cells.Vclamp,non_mPFCBLA_cells.Vclamp,rand_cells.Vclamp},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','Rand'})
ylabel('V_c_l_a_m_p (mV)')
[p_kw,tbl_kw,stats_kw] = kruskalwallis([mPFCBLA_cells.Vclamp;rand_cells.Vclamp;non_mPFCBLA_cells.Vclamp],...
    [repmat({'mPFC-BLA'},size(mPFCBLA_cells.Vclamp));repmat({'Random'},size(rand_cells.Vclamp));repmat({'Non-mPFC-BLA'},size(non_mPFCBLA_cells.Vclamp))],'off');
c_kw = multcompare(stats_kw,'Display','off');
title(['p_m_B_-_v_s_-_r_n_d = ' num2str(c_kw(1,6),3) '; p_m_B_-_v_s_-_n_-_m_B = ' num2str(c_kw(2,6),3) '; p_r_n_d_-_v_s_-_n_-_m_B = ' num2str(c_kw(3,6),3)])
subplot(3,5,15);	hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_cells.Iholding,'omitnan') mean(non_mPFCBLA_cells.Iholding,'omitnan') mean(rand_cells.Iholding,'omitnan')],...
    [std(mPFCBLA_cells.Iholding,'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.Iholding))),...
    std(non_mPFCBLA_cells.Iholding,'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.Iholding))),...
    std(rand_cells.Iholding,'omitnan')/sqrt(sum(~isnan(rand_cells.Iholding)))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',7)
plotSpread({mPFCBLA_cells.Iholding,non_mPFCBLA_cells.Iholding,rand_cells.Iholding},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','Rand'})
ylabel('I_h_o_l_d_i_n_g (pA)')
[p_kw,tbl_kw,stats_kw] = kruskalwallis([mPFCBLA_cells.Iholding;rand_cells.Iholding;non_mPFCBLA_cells.Iholding],...
    [repmat({'mPFC-BLA'},size(mPFCBLA_cells.Iholding));repmat({'Random'},size(rand_cells.Iholding));repmat({'Non-mPFC-BLA'},size(non_mPFCBLA_cells.Iholding))],'off');
c_kw = multcompare(stats_kw,'Display','off');
title(['p_m_B_-_v_s_-_r_n_d = ' num2str(c_kw(1,6),3) '; p_m_B_-_v_s_-_n_-_m_B = ' num2str(c_kw(2,6),3) '; p_r_n_d_-_v_s_-_n_-_m_B = ' num2str(c_kw(3,6),3)])
for i = 1:15
    set(findall(subplot(3,5,i),'type','line','color',[0 0 0]),'markerSize',plotSpreadMarkerSize)
end
popupmore(fEphysProps)
xDataReg = all_cells.conn_p.in_r(:,r_ind_slct);
yDataReg = all_cells.mean_input.in_r(:,r_ind_max);
xDataReg = xDataReg(~isnan(yDataReg));  yDataReg = yDataReg(~isnan(yDataReg));  % Taking only cells with inputs
[bLin,bLinInt] = regress(yDataReg,[ones(size(yDataReg)) xDataReg]);
[Rcorr,pcorr] = corrcoef(xDataReg,yDataReg,'Rows','complete');
xRange = [min(xDataReg) max(xDataReg)]; clrReg = [1 0 1];
figure; hold on
fill([xRange fliplr(xRange)],[bLinInt(1,1)+bLinInt(2,1)*xRange,fliplr(bLinInt(1,2)+bLinInt(2,2)*xRange)],clrReg+0.7*(1-clrReg),'linestyle','none')
plot(xRange,bLin(1)+bLin(2)*xRange,'color',clrReg)
scatter(non_mPFCBLA_cells.conn_p.in_r(:,r_ind_slct),non_mPFCBLA_cells.mean_input.in_r(:,r_ind_max),sctrSz,non_mPFCBLA_cells.clr,'linewidth',sctrLnWidth)
scatter(rand_cells.conn_p.in_r(:,r_ind_slct),rand_cells.mean_input.in_r(:,r_ind_max),sctrSz,rand_cells.clr,'linewidth',sctrLnWidth)
scatter(mPFCBLA_cells.conn_p.in_r(:,r_ind_slct),mPFCBLA_cells.mean_input.in_r(:,r_ind_max),sctrSz,mPFCBLA_cells.clr,'linewidth',sctrLnWidth)
xlabel(['P(conn) in r=' num2str(selected_r) ' \mum']);	ylabel('Mean conn. strength (pA)')
title(['R=' num2str(Rcorr(1,2),2) ', p=' num2str(pcorr(1,2),2)])
ylim([-1.2 62])

%% Stats by layers (without L3)
% connFields = {'conn_p','weighted_input','mean_input'};
connFields = {'weighted_input'};
for iField = 1:length(connFields)
    anovaData = [...
        mPFCBLA_cells.(connFields{iField}).in_r(mPFCBLA_cells.L2_inds,r_ind_slct);
        mPFCBLA_cells.(connFields{iField}).in_r(mPFCBLA_cells.L56_inds,r_ind_slct);
        rand_cells.(connFields{iField}).in_r(rand_cells.L2_inds,r_ind_slct);
        rand_cells.(connFields{iField}).in_r(rand_cells.L56_inds,r_ind_slct);
        non_mPFCBLA_cells.(connFields{iField}).in_r(non_mPFCBLA_cells.L2_inds,r_ind_slct);
        non_mPFCBLA_cells.(connFields{iField}).in_r(non_mPFCBLA_cells.L56_inds,r_ind_slct)];
    anovaGroupAll = [...
        repmat({'mPFCBLA-L2'},size(mPFCBLA_cells.(connFields{iField}).in_r(mPFCBLA_cells.L2_inds,r_ind_slct)));
        repmat({'mPFCBLA-L56'},size(mPFCBLA_cells.(connFields{iField}).in_r(mPFCBLA_cells.L56_inds,r_ind_slct)));
        repmat({'Random-L2'},size(rand_cells.(connFields{iField}).in_r(rand_cells.L2_inds,r_ind_slct)));
        repmat({'Random-L56'},size(rand_cells.(connFields{iField}).in_r(rand_cells.L56_inds,r_ind_slct)));
        repmat({'non-mPFCBLA-L2'},size(non_mPFCBLA_cells.(connFields{iField}).in_r(non_mPFCBLA_cells.L2_inds,r_ind_slct)));
        repmat({'non-mPFCBLA-L56'},size(non_mPFCBLA_cells.(connFields{iField}).in_r(non_mPFCBLA_cells.L56_inds,r_ind_slct)))];
    anovaGroupCellType = [...
        repmat({'mPFCBLA'},size(mPFCBLA_cells.(connFields{iField}).in_r(mPFCBLA_cells.L2_inds,r_ind_slct)));
        repmat({'mPFCBLA'},size(mPFCBLA_cells.(connFields{iField}).in_r(mPFCBLA_cells.L56_inds,r_ind_slct)));
        repmat({'Random'},size(rand_cells.(connFields{iField}).in_r(rand_cells.L2_inds,r_ind_slct)));
        repmat({'Random'},size(rand_cells.(connFields{iField}).in_r(rand_cells.L56_inds,r_ind_slct)));
        repmat({'non-mPFCBLA'},size(non_mPFCBLA_cells.(connFields{iField}).in_r(non_mPFCBLA_cells.L2_inds,r_ind_slct)));
        repmat({'non-mPFCBLA'},size(non_mPFCBLA_cells.(connFields{iField}).in_r(non_mPFCBLA_cells.L56_inds,r_ind_slct)))];
    anovaGroupLayer = [...
        repmat({'L2'},size(mPFCBLA_cells.(connFields{iField}).in_r(mPFCBLA_cells.L2_inds,r_ind_slct)));
        repmat({'L56'},size(mPFCBLA_cells.(connFields{iField}).in_r(mPFCBLA_cells.L56_inds,r_ind_slct)));
        repmat({'L2'},size(rand_cells.(connFields{iField}).in_r(rand_cells.L2_inds,r_ind_slct)));
        repmat({'L56'},size(rand_cells.(connFields{iField}).in_r(rand_cells.L56_inds,r_ind_slct)));
        repmat({'L2'},size(non_mPFCBLA_cells.(connFields{iField}).in_r(non_mPFCBLA_cells.L2_inds,r_ind_slct)));
        repmat({'L56'},size(non_mPFCBLA_cells.(connFields{iField}).in_r(non_mPFCBLA_cells.L56_inds,r_ind_slct)))];
    figure; [p_anova,tbl_anova,stats_anova,terms_anova] =...
        anovan(anovaData,{anovaGroupCellType anovaGroupLayer},'model',2,'varnames',{'Cell type','Layer'});
    set(gcf,'Name',connFields{iField})
    c_anova = multcompare(stats_anova,'Dimension',[1 2]);
end
f_input_by_layer = figure;  hold on;    errorbar((1:6)+0.2,...
    [mean(mPFCBLA_cells.weighted_input.in_r(mPFCBLA_cells.L2_inds,r_ind_slct),'omitnan'),...
    mean(mPFCBLA_cells.weighted_input.in_r(mPFCBLA_cells.L56_inds,r_ind_slct),'omitnan'),...
    mean(non_mPFCBLA_cells.weighted_input.in_r(non_mPFCBLA_cells.L2_inds,r_ind_slct),'omitnan'),...
    mean(non_mPFCBLA_cells.weighted_input.in_r(non_mPFCBLA_cells.L56_inds,r_ind_slct),'omitnan'),...
    mean(rand_cells.weighted_input.in_r(rand_cells.L2_inds,r_ind_slct),'omitnan'),...
    mean(rand_cells.weighted_input.in_r(rand_cells.L56_inds,r_ind_slct),'omitnan')],...
    [std(mPFCBLA_cells.weighted_input.in_r(mPFCBLA_cells.L2_inds,r_ind_slct),'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.weighted_input.in_r(mPFCBLA_cells.L2_inds,r_ind_slct)))),...
    std(mPFCBLA_cells.weighted_input.in_r(mPFCBLA_cells.L56_inds,r_ind_slct),'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.weighted_input.in_r(mPFCBLA_cells.L56_inds,r_ind_slct)))),...
    std(non_mPFCBLA_cells.weighted_input.in_r(non_mPFCBLA_cells.L2_inds,r_ind_slct),'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.weighted_input.in_r(non_mPFCBLA_cells.L2_inds,r_ind_slct)))),...
    std(non_mPFCBLA_cells.weighted_input.in_r(non_mPFCBLA_cells.L56_inds,r_ind_slct),'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.weighted_input.in_r(non_mPFCBLA_cells.L56_inds,r_ind_slct)))),...
    std(rand_cells.weighted_input.in_r(rand_cells.L2_inds,r_ind_slct),'omitnan')/sqrt(sum(~isnan(rand_cells.weighted_input.in_r(rand_cells.L2_inds,r_ind_slct)))),...
    std(rand_cells.weighted_input.in_r(rand_cells.L56_inds,r_ind_slct),'omitnan')/sqrt(sum(~isnan(rand_cells.weighted_input.in_r(rand_cells.L56_inds,r_ind_slct))))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',7)
plotSpread({mPFCBLA_cells.weighted_input.in_r(mPFCBLA_cells.L2_inds,r_ind_slct),...
    mPFCBLA_cells.weighted_input.in_r(mPFCBLA_cells.L56_inds,r_ind_slct),...
    non_mPFCBLA_cells.weighted_input.in_r(non_mPFCBLA_cells.L2_inds,r_ind_slct),...
    non_mPFCBLA_cells.weighted_input.in_r(non_mPFCBLA_cells.L56_inds,r_ind_slct),...
    rand_cells.weighted_input.in_r(rand_cells.L2_inds,r_ind_slct),...
    rand_cells.weighted_input.in_r(rand_cells.L56_inds,r_ind_slct)},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mB L2','mB L5/6','non-mB L2','non-mB L5/6','rnd L2','rnd L5/6'})
ylabel(['Weighted input (pA) in r=' num2str(selected_r) ' \mum'])
set(findall(f_input_by_layer,'type','line','color',[0 0 0]),'markerSize',plotSpreadMarkerSize)

%% Plots and stats by direction
y_lim_direction = [0 5];    barTicks = [0.85 2.15]; xLimDir = [0.65 2.35];
pDV_mPFCBLA_cells_L3 = signrank(mPFCBLA_cells.weighted_input.ventral(mPFCBLA_cells.L3_inds),mPFCBLA_cells.weighted_input.dorsal(mPFCBLA_cells.L3_inds));
pDV_non_mPFCBLA_cells_L3 = signrank(non_mPFCBLA_cells.weighted_input.ventral(non_mPFCBLA_cells.L3_inds),non_mPFCBLA_cells.weighted_input.dorsal(non_mPFCBLA_cells.L3_inds));
pML_mPFCBLA_cells_Lall = signrank(mPFCBLA_cells.weighted_input.medial,mPFCBLA_cells.weighted_input.lateral);
pML_non_mPFCBLA_cells_Lall = signrank(non_mPFCBLA_cells.weighted_input.medial,non_mPFCBLA_cells.weighted_input.lateral);
pML_rand_cells_L56 = signrank(rand_cells.weighted_input.medial(rand_cells.L56_inds),rand_cells.weighted_input.lateral(rand_cells.L56_inds));
pML_rand_cells_Lall = signrank(rand_cells.weighted_input.medial,rand_cells.weighted_input.lateral);
mPFCBLA_cells.pML = signrank(mPFCBLA_cells.weighted_input.medial,mPFCBLA_cells.weighted_input.lateral);
rand_cells.pML = signrank(rand_cells.weighted_input.medial,rand_cells.weighted_input.lateral);
non_mPFCBLA_cells.pML = signrank(non_mPFCBLA_cells.weighted_input.medial,non_mPFCBLA_cells.weighted_input.lateral);
mPFCBLA_cells.pDV = signrank(mPFCBLA_cells.weighted_input.dorsal,mPFCBLA_cells.weighted_input.ventral);
rand_cells.pDV = signrank(rand_cells.weighted_input.dorsal,rand_cells.weighted_input.ventral);
non_mPFCBLA_cells.pDV = signrank(non_mPFCBLA_cells.weighted_input.dorsal,non_mPFCBLA_cells.weighted_input.ventral);
f_direction_conn = figure;  subplot(2,3,1); hold on
errorbar(barTicks,[mean(mPFCBLA_cells.weighted_input.medial,'omitnan') mean(mPFCBLA_cells.weighted_input.lateral,'omitnan')],...
    [std(mPFCBLA_cells.weighted_input.medial,'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.weighted_input.medial))) ...
    std(mPFCBLA_cells.weighted_input.lateral,'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.weighted_input.lateral)))],...
    '+','linewidth',2,'markersize',10,'color',mPFCBLA_cells.clr,'capsize',7)
plot([1 2],[mPFCBLA_cells.weighted_input.medial';mPFCBLA_cells.weighted_input.lateral'],'color',mPFCBLA_cells.clr)
xticks(barTicks);  xticklabels({'Medial','Lateral'});  xlim(xLimDir);    ylim(y_lim_direction)
xlabel('Direction');    ylabel('Weighted input (pA)');  title(['All layers, p=' num2str(mPFCBLA_cells.pML,3)])
subplot(2,3,3); hold on
errorbar(barTicks,[mean(rand_cells.weighted_input.medial,'omitnan') mean(rand_cells.weighted_input.lateral,'omitnan')],...
    [std(rand_cells.weighted_input.medial,'omitnan')/sqrt(sum(~isnan(rand_cells.weighted_input.medial))) ...
    std(rand_cells.weighted_input.lateral,'omitnan')/sqrt(sum(~isnan(rand_cells.weighted_input.lateral)))],...
    '+','linewidth',2,'markersize',10,'color',rand_cells.clr,'capsize',7)
plot([1 2],[rand_cells.weighted_input.medial';rand_cells.weighted_input.lateral'],'color',rand_cells.clr)
xticks(barTicks);  xticklabels({'Medial','Lateral'});  xlim(xLimDir);    ylim(y_lim_direction)
xlabel('Direction');    ylabel('Weighted input (pA)');  title(['All layers, p=' num2str(rand_cells.pML,3)])
subplot(2,3,2); hold on
errorbar(barTicks,[mean(non_mPFCBLA_cells.weighted_input.medial,'omitnan') mean(non_mPFCBLA_cells.weighted_input.lateral,'omitnan')],...
    [std(non_mPFCBLA_cells.weighted_input.medial,'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.weighted_input.medial))) ...
    std(non_mPFCBLA_cells.weighted_input.lateral,'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.weighted_input.lateral)))],...
    '+','linewidth',2,'markersize',10,'color',non_mPFCBLA_cells.clr,'capsize',7)
plot([1 2],[non_mPFCBLA_cells.weighted_input.medial';non_mPFCBLA_cells.weighted_input.lateral'],'color',non_mPFCBLA_cells.clr)
xticks(barTicks);  xticklabels({'Medial','Lateral'});  xlim(xLimDir);    ylim(y_lim_direction)
xlabel('Direction');    ylabel('Weighted input (pA)');  title(['All layers, p=' num2str(non_mPFCBLA_cells.pML,3)])
subplot(2,3,4); hold on
errorbar(barTicks,[mean(mPFCBLA_cells.weighted_input.dorsal,'omitnan') mean(mPFCBLA_cells.weighted_input.ventral,'omitnan')],...
    [std(mPFCBLA_cells.weighted_input.dorsal,'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.weighted_input.dorsal))) ...
    std(mPFCBLA_cells.weighted_input.ventral,'omitnan')/sqrt(sum(~isnan(mPFCBLA_cells.weighted_input.ventral)))],...
    '+','linewidth',2,'markersize',10,'color',mPFCBLA_cells.clr,'capsize',7)
plot([1 2],[mPFCBLA_cells.weighted_input.dorsal';mPFCBLA_cells.weighted_input.ventral'],'color',mPFCBLA_cells.clr)
xticks(barTicks);  xticklabels({'Dorsal','Ventral'});  xlim(xLimDir);    ylim(y_lim_direction)
xlabel('Direction');    ylabel('Weighted input (pA)');  title(['All layers, p=' num2str(mPFCBLA_cells.pDV,3)])
subplot(2,3,6); hold on
errorbar(barTicks,[mean(rand_cells.weighted_input.dorsal,'omitnan') mean(rand_cells.weighted_input.ventral,'omitnan')],...
    [std(rand_cells.weighted_input.dorsal,'omitnan')/sqrt(sum(~isnan(rand_cells.weighted_input.dorsal))) ...
    std(rand_cells.weighted_input.ventral,'omitnan')/sqrt(sum(~isnan(rand_cells.weighted_input.ventral)))],...
    '+','linewidth',2,'markersize',10,'color',rand_cells.clr,'capsize',7)
plot([1 2],[rand_cells.weighted_input.dorsal';rand_cells.weighted_input.ventral'],'color',rand_cells.clr)
xticks(barTicks);  xticklabels({'Dorsal','Ventral'});  xlim(xLimDir);    ylim(y_lim_direction)
xlabel('Direction');    ylabel('Weighted input (pA)');  title(['All layers, p=' num2str(rand_cells.pDV,3)])
subplot(2,3,5); hold on
errorbar(barTicks,[mean(non_mPFCBLA_cells.weighted_input.dorsal,'omitnan') mean(non_mPFCBLA_cells.weighted_input.ventral,'omitnan')],...
    [std(non_mPFCBLA_cells.weighted_input.dorsal,'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.weighted_input.dorsal))) ...
    std(non_mPFCBLA_cells.weighted_input.ventral,'omitnan')/sqrt(sum(~isnan(non_mPFCBLA_cells.weighted_input.ventral)))],...
    '+','linewidth',2,'markersize',10,'color',non_mPFCBLA_cells.clr,'capsize',7)
plot([1 2],[non_mPFCBLA_cells.weighted_input.dorsal';non_mPFCBLA_cells.weighted_input.ventral'],'color',non_mPFCBLA_cells.clr)
xticks(barTicks);  xticklabels({'Dorsal','Ventral'});  xlim(xLimDir);    ylim(y_lim_direction)
xlabel('Direction');    ylabel('Weighted input (pA)');  title(['All layers, p=' num2str(non_mPFCBLA_cells.pDV,3)])
popupmore(f_direction_conn)

%% Plots for weighted inputs by layer
plotSpreadBinWidth = 0.2;   plotSpreadMarkerSize = 10;  capSize = 7;
[~,r_ind_max_Ls] = max(r_around_cell_Ls);
f_layer_connWeighted_plots = figure;  subplot(3,3,1);	hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L2toL2(:,r_ind_max_Ls),'omitnan'),...
    mean(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L2toL2(:,r_ind_max_Ls),'omitnan'),...
    mean(random_to_random.weighted_input_in_r.L2toL2(:,r_ind_max_Ls),'omitnan')],...
    [std(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L2toL2(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L2toL2(:,r_ind_max_Ls)))),...
    std(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L2toL2(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L2toL2(:,r_ind_max_Ls)))),...
    std(random_to_random.weighted_input_in_r.L2toL2(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(random_to_random.weighted_input_in_r.L2toL2(:,r_ind_max_Ls))))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',capSize)
plotSpread({mPFCBLA_to_mPFCBLA.weighted_input_in_r.L2toL2(:,r_ind_max_Ls),...
    mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L2toL2(:,r_ind_max_Ls),...
    random_to_random.weighted_input_in_r.L2toL2(:,r_ind_max_Ls)},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','random'});	ylabel('Weighted input (pA)')
title('L2 to L2')
subplot(3,3,5);	hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L3toL3(:,r_ind_max_Ls),'omitnan'),...
    mean(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L3toL3(:,r_ind_max_Ls),'omitnan'),...
    mean(random_to_random.weighted_input_in_r.L3toL3(:,r_ind_max_Ls),'omitnan')],...
    [std(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L3toL3(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L3toL3(:,r_ind_max_Ls)))),...
    std(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L3toL3(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L3toL3(:,r_ind_max_Ls)))),...
    std(random_to_random.weighted_input_in_r.L3toL3(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(random_to_random.weighted_input_in_r.L3toL3(:,r_ind_max_Ls))))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',capSize)
plotSpread({mPFCBLA_to_mPFCBLA.weighted_input_in_r.L3toL3(:,r_ind_max_Ls),...
    mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L3toL3(:,r_ind_max_Ls),...
    random_to_random.weighted_input_in_r.L3toL3(:,r_ind_max_Ls)},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','random'});  ylabel('Weighted input (pA)')
title('L3 to L3')
subplot(3,3,9);	hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L56toL56(:,r_ind_max_Ls),'omitnan'),...
    mean(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L56toL56(:,r_ind_max_Ls),'omitnan'),...
    mean(random_to_random.weighted_input_in_r.L56toL56(:,r_ind_max_Ls),'omitnan')],...
    [std(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L56toL56(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L56toL56(:,r_ind_max_Ls)))),...
    std(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L56toL56(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L56toL56(:,r_ind_max_Ls)))),...
    std(random_to_random.weighted_input_in_r.L56toL56(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(random_to_random.weighted_input_in_r.L56toL56(:,r_ind_max_Ls))))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',capSize)
plotSpread({mPFCBLA_to_mPFCBLA.weighted_input_in_r.L56toL56(:,r_ind_max_Ls),...
    mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L56toL56(:,r_ind_max_Ls),...
    random_to_random.weighted_input_in_r.L56toL56(:,r_ind_max_Ls)},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','random'});  ylabel('Weighted input (pA)')
title('L5/6 to L5/6')
subplot(3,3,2);	hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L2toL3(:,r_ind_max_Ls),'omitnan'),...
    mean(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L2toL3(:,r_ind_max_Ls),'omitnan'),...
    mean(random_to_random.weighted_input_in_r.L2toL3(:,r_ind_max_Ls),'omitnan')],...
    [std(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L2toL3(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L2toL3(:,r_ind_max_Ls)))),...
    std(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L2toL3(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L2toL3(:,r_ind_max_Ls)))),...
    std(random_to_random.weighted_input_in_r.L2toL3(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(random_to_random.weighted_input_in_r.L2toL3(:,r_ind_max_Ls))))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',capSize)
plotSpread({mPFCBLA_to_mPFCBLA.weighted_input_in_r.L2toL3(:,r_ind_max_Ls),...
    mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L2toL3(:,r_ind_max_Ls),...
    random_to_random.weighted_input_in_r.L2toL3(:,r_ind_max_Ls)},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','random'});  ylabel('Weighted input (pA)')
title('L2 to L3')
subplot(3,3,6);	hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L3toL56(:,r_ind_max_Ls),'omitnan'),...
    mean(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L3toL56(:,r_ind_max_Ls),'omitnan'),...
    mean(random_to_random.weighted_input_in_r.L3toL56(:,r_ind_max_Ls),'omitnan')],...
    [std(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L3toL56(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L3toL56(:,r_ind_max_Ls)))),...
    std(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L3toL56(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L3toL56(:,r_ind_max_Ls)))),...
    std(random_to_random.weighted_input_in_r.L3toL56(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(random_to_random.weighted_input_in_r.L3toL56(:,r_ind_max_Ls))))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',capSize)
plotSpread({mPFCBLA_to_mPFCBLA.weighted_input_in_r.L3toL56(:,r_ind_max_Ls),...
    mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L3toL56(:,r_ind_max_Ls),...
    random_to_random.weighted_input_in_r.L3toL56(:,r_ind_max_Ls)},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','random'});  ylabel('Weighted input (pA)')
title('L3 to L5/6')
subplot(3,3,3);	hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L2toL56(:,r_ind_max_Ls),'omitnan'),...
    mean(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L2toL56(:,r_ind_max_Ls),'omitnan'),...
    mean(random_to_random.weighted_input_in_r.L2toL56(:,r_ind_max_Ls),'omitnan')],...
    [std(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L2toL56(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L2toL56(:,r_ind_max_Ls)))),...
    std(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L2toL56(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L2toL56(:,r_ind_max_Ls)))),...
    std(random_to_random.weighted_input_in_r.L2toL56(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(random_to_random.weighted_input_in_r.L2toL56(:,r_ind_max_Ls))))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',capSize)
plotSpread({mPFCBLA_to_mPFCBLA.weighted_input_in_r.L2toL56(:,r_ind_max_Ls),...
    mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L2toL56(:,r_ind_max_Ls),...
    random_to_random.weighted_input_in_r.L2toL56(:,r_ind_max_Ls)},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','random'});  ylabel('Weighted input (pA)')
title('L2 to L5/6')
subplot(3,3,4);	hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L3toL2(:,r_ind_max_Ls),'omitnan'),...
    mean(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L3toL2(:,r_ind_max_Ls),'omitnan'),...
    mean(random_to_random.weighted_input_in_r.L3toL2(:,r_ind_max_Ls),'omitnan')],...
    [std(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L3toL2(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L3toL2(:,r_ind_max_Ls)))),...
    std(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L3toL2(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L3toL2(:,r_ind_max_Ls)))),...
    std(random_to_random.weighted_input_in_r.L3toL2(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(random_to_random.weighted_input_in_r.L3toL2(:,r_ind_max_Ls))))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',capSize)
plotSpread({mPFCBLA_to_mPFCBLA.weighted_input_in_r.L3toL2(:,r_ind_max_Ls),...
    mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L3toL2(:,r_ind_max_Ls),...
    random_to_random.weighted_input_in_r.L3toL2(:,r_ind_max_Ls)},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','random'});  ylabel('Weighted input (pA)')
title('L3 to L2')
subplot(3,3,8);	hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L56toL3(:,r_ind_max_Ls),'omitnan'),...
    mean(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L56toL3(:,r_ind_max_Ls),'omitnan'),...
    mean(random_to_random.weighted_input_in_r.L56toL3(:,r_ind_max_Ls),'omitnan')],...
    [std(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L56toL3(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L56toL3(:,r_ind_max_Ls)))),...
    std(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L56toL3(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L56toL3(:,r_ind_max_Ls)))),...
    std(random_to_random.weighted_input_in_r.L56toL3(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(random_to_random.weighted_input_in_r.L56toL3(:,r_ind_max_Ls))))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',capSize)
plotSpread({mPFCBLA_to_mPFCBLA.weighted_input_in_r.L56toL3(:,r_ind_max_Ls),...
    mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L56toL3(:,r_ind_max_Ls),...
    random_to_random.weighted_input_in_r.L56toL3(:,r_ind_max_Ls)},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','random'});  ylabel('Weighted input (pA)')
title('L5/6 to L3')
subplot(3,3,7);	hold on
errorbar((1:3)+0.2,[mean(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L56toL2(:,r_ind_max_Ls),'omitnan'),...
    mean(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L56toL2(:,r_ind_max_Ls),'omitnan'),...
    mean(random_to_random.weighted_input_in_r.L56toL2(:,r_ind_max_Ls),'omitnan')],...
    [std(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L56toL2(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L56toL2(:,r_ind_max_Ls)))),...
    std(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L56toL2(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L56toL2(:,r_ind_max_Ls)))),...
    std(random_to_random.weighted_input_in_r.L56toL2(:,r_ind_max_Ls),'omitnan')/sqrt(sum(~isnan(random_to_random.weighted_input_in_r.L56toL2(:,r_ind_max_Ls))))],...
    '+','linewidth',2,'markersize',10,'color',[0 0 0],'capsize',capSize)
plotSpread({mPFCBLA_to_mPFCBLA.weighted_input_in_r.L56toL2(:,r_ind_max_Ls),...
    mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L56toL2(:,r_ind_max_Ls),...
    random_to_random.weighted_input_in_r.L56toL2(:,r_ind_max_Ls)},...
    'distributionMarkers','.','distributionColors',[0 0 0],'binWidth',plotSpreadBinWidth)
xticklabels({'mPFC-BLA','non-mPFC-BLA','random'});  ylabel('Weighted input (pA)')
title('L5/6 to L2')
for i = 1:9
    set(findall(subplot(3,3,i),'type','line','color',[0 0 0]),'markerSize',plotSpreadMarkerSize)
end
popupmore(f_layer_connWeighted_plots)
mPFCBLA_to_mPFCBLA.weighted_input_in_r.heat_mat = ...
    [mean(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L2toL2(:,r_ind_max_Ls),'omitnan'),mean(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L2toL3(:,r_ind_max_Ls),'omitnan'),mean(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L2toL56(:,r_ind_max_Ls),'omitnan');...
    mean(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L3toL2(:,r_ind_max_Ls),'omitnan'),mean(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L3toL3(:,r_ind_max_Ls),'omitnan'),mean(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L3toL56(:,r_ind_max_Ls),'omitnan');...
    mean(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L56toL2(:,r_ind_max_Ls),'omitnan'),mean(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L56toL3(:,r_ind_max_Ls),'omitnan'),mean(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L56toL56(:,r_ind_max_Ls),'omitnan')];
mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.heat_mat = ...
    [mean(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L2toL2(:,r_ind_max_Ls),'omitnan'),mean(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L2toL3(:,r_ind_max_Ls),'omitnan'),mean(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L2toL56(:,r_ind_max_Ls),'omitnan');...
    mean(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L3toL2(:,r_ind_max_Ls),'omitnan'),mean(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L3toL3(:,r_ind_max_Ls),'omitnan'),mean(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L3toL56(:,r_ind_max_Ls),'omitnan');...
    mean(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L56toL2(:,r_ind_max_Ls),'omitnan'),mean(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L56toL3(:,r_ind_max_Ls),'omitnan'),mean(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L56toL56(:,r_ind_max_Ls),'omitnan')];
random_to_random.weighted_input_in_r.heat_mat = ...
    [mean(random_to_random.weighted_input_in_r.L2toL2(:,r_ind_max_Ls),'omitnan'),mean(random_to_random.weighted_input_in_r.L2toL3(:,r_ind_max_Ls),'omitnan'),mean(random_to_random.weighted_input_in_r.L2toL56(:,r_ind_max_Ls),'omitnan');...
    mean(random_to_random.weighted_input_in_r.L3toL2(:,r_ind_max_Ls),'omitnan'),mean(random_to_random.weighted_input_in_r.L3toL3(:,r_ind_max_Ls),'omitnan'),mean(random_to_random.weighted_input_in_r.L3toL56(:,r_ind_max_Ls),'omitnan');...
    mean(random_to_random.weighted_input_in_r.L56toL2(:,r_ind_max_Ls),'omitnan'),mean(random_to_random.weighted_input_in_r.L56toL3(:,r_ind_max_Ls),'omitnan'),mean(random_to_random.weighted_input_in_r.L56toL56(:,r_ind_max_Ls),'omitnan')];
mPFCBLA_to_mPFCBLA.weighted_input_in_r.heat_mat_median = ...
    [median(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L2toL2(:,r_ind_max_Ls),'omitnan'),median(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L2toL3(:,r_ind_max_Ls),'omitnan'),median(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L2toL56(:,r_ind_max_Ls),'omitnan');...
    median(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L3toL2(:,r_ind_max_Ls),'omitnan'),median(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L3toL3(:,r_ind_max_Ls),'omitnan'),median(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L3toL56(:,r_ind_max_Ls),'omitnan');...
    median(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L56toL2(:,r_ind_max_Ls),'omitnan'),median(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L56toL3(:,r_ind_max_Ls),'omitnan'),median(mPFCBLA_to_mPFCBLA.weighted_input_in_r.L56toL56(:,r_ind_max_Ls),'omitnan')];
mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.heat_mat_median = ...
    [median(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L2toL2(:,r_ind_max_Ls),'omitnan'),median(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L2toL3(:,r_ind_max_Ls),'omitnan'),median(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L2toL56(:,r_ind_max_Ls),'omitnan');...
    median(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L3toL2(:,r_ind_max_Ls),'omitnan'),median(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L3toL3(:,r_ind_max_Ls),'omitnan'),median(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L3toL56(:,r_ind_max_Ls),'omitnan');...
    median(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L56toL2(:,r_ind_max_Ls),'omitnan'),median(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L56toL3(:,r_ind_max_Ls),'omitnan'),median(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.L56toL56(:,r_ind_max_Ls),'omitnan')];
random_to_random.weighted_input_in_r.heat_mat_median = ...
    [median(random_to_random.weighted_input_in_r.L2toL2(:,r_ind_max_Ls),'omitnan'),median(random_to_random.weighted_input_in_r.L2toL3(:,r_ind_max_Ls),'omitnan'),median(random_to_random.weighted_input_in_r.L2toL56(:,r_ind_max_Ls),'omitnan');...
    median(random_to_random.weighted_input_in_r.L3toL2(:,r_ind_max_Ls),'omitnan'),median(random_to_random.weighted_input_in_r.L3toL3(:,r_ind_max_Ls),'omitnan'),median(random_to_random.weighted_input_in_r.L3toL56(:,r_ind_max_Ls),'omitnan');...
    median(random_to_random.weighted_input_in_r.L56toL2(:,r_ind_max_Ls),'omitnan'),median(random_to_random.weighted_input_in_r.L56toL3(:,r_ind_max_Ls),'omitnan'),median(random_to_random.weighted_input_in_r.L56toL56(:,r_ind_max_Ls),'omitnan')];
f_layer_connWeighted_heat_maps = figure;	subplot(2,3,1)
imagesc(mPFCBLA_to_mPFCBLA.weighted_input_in_r.heat_mat,'AlphaData',~isnan(mPFCBLA_to_mPFCBLA.weighted_input_in_r.heat_mat));	colormap jet
xlabel('To');	ylabel('From'); daspect([1 1 1]);   box off
xticklabels({'L2','L3','L56'}); yticklabels({'L2','L3','L56'})
C = colorbar;	ylabel(C,'Weighted input (pA)')
title('mPFC-BLA to mPFC-BLA cells (mean)');    set(gca,'xaxisLocation','top')
subplot(2,3,2)
imagesc(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.heat_mat,'AlphaData',~isnan(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.heat_mat));	colormap jet
xlabel('To');	ylabel('From'); daspect([1 1 1]);   box off
xticklabels({'L2','L3','L56'}); yticklabels({'L2','L3','L56'})
C = colorbar;	ylabel(C,'Weighted input (pA)')
title('mPFC-BLA to non-mPFC-BLA cells (mean)');    set(gca,'xaxisLocation','top')
subplot(2,3,3)
imagesc(random_to_random.weighted_input_in_r.heat_mat,'AlphaData',~isnan(random_to_random.weighted_input_in_r.heat_mat));	colormap jet
xlabel('To');	ylabel('From'); daspect([1 1 1]);   box off
xticklabels({'L2','L3','L56'}); yticklabels({'L2','L3','L56'})
C = colorbar;	ylabel(C,'Weighted input (pA)')
title('Random to random cells (mean)');    set(gca,'xaxisLocation','top')
subplot(2,3,4)
imagesc(mPFCBLA_to_mPFCBLA.weighted_input_in_r.heat_mat_median,'AlphaData',~isnan(mPFCBLA_to_mPFCBLA.weighted_input_in_r.heat_mat_median));	colormap jet
xlabel('To');	ylabel('From'); daspect([1 1 1]);   box off
xticklabels({'L2','L3','L56'}); yticklabels({'L2','L3','L56'})
C = colorbar;	ylabel(C,'Weighted input (pA)')
title('mPFC-BLA to mPFC-BLA cells (median)');    set(gca,'xaxisLocation','top')
subplot(2,3,5)
imagesc(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.heat_mat_median,'AlphaData',~isnan(mPFCBLA_to_nonmPFCBLA.weighted_input_in_r.heat_mat_median));	colormap jet
xlabel('To');	ylabel('From'); daspect([1 1 1]);   box off
xticklabels({'L2','L3','L56'}); yticklabels({'L2','L3','L56'})
C = colorbar;	ylabel(C,'Weighted input (pA)')
title('mPFC-BLA to non-mPFC-BLA cells (median)');    set(gca,'xaxisLocation','top')
subplot(2,3,6)
imagesc(random_to_random.weighted_input_in_r.heat_mat_median,'AlphaData',~isnan(random_to_random.weighted_input_in_r.heat_mat_median));	colormap jet
xlabel('To');	ylabel('From'); daspect([1 1 1]);   box off
xticklabels({'L2','L3','L56'}); yticklabels({'L2','L3','L56'})
C = colorbar;	ylabel(C,'Weighted input (pA)')
title('Random to random cells (median)');    set(gca,'xaxisLocation','top')
popupmore(f_layer_connWeighted_heat_maps)



